# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
